### ISSUE TITLE
Default favicon for docs

### ISSUE THREAD

**Issue by raajnadar** [callstack/component-docs#16]
There should be a default favicon for each docs. So that the user gets control to override the default favicon.

@satya164 any idea to make it flexible in such a way that the favicon provided by the user is used in each page in paper docs?? There is not common file where the html tag can be inserted or else we need to put the path of favicon in each meta export. 

https://github.com/callstack/react-native-paper/issues/738

**Comment by satya164** [comment]
We can add an option. Or maybe we can just copy the favicon to `dist/` when publishing in paper.

**Comment by raajnadar** [comment]
Closing this issue the best option is to move favicon during build time.
